[theme]
primaryColor = "#54CFD4"
backgroundColor = "#ffffff" # General background color, applies to the main content area
secondaryBackgroundColor = "#ffffff" # Sidebar background color
textColor = "#31333F"
font = "sans serif" # Options: "serif", "sans serif", "monospace"


